/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const LogisterLazyImport = createFileRoute('/logister')()
const ChartLazyImport = createFileRoute('/chart')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const LogisterLazyRoute = LogisterLazyImport.update({
  id: '/logister',
  path: '/logister',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/logister.lazy').then((d) => d.Route))

const ChartLazyRoute = ChartLazyImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/chart.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/chart': {
      id: '/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ChartLazyImport
      parentRoute: typeof rootRoute
    }
    '/logister': {
      id: '/logister'
      path: '/logister'
      fullPath: '/logister'
      preLoaderRoute: typeof LogisterLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/chart': typeof ChartLazyRoute
  '/logister': typeof LogisterLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/chart': typeof ChartLazyRoute
  '/logister': typeof LogisterLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/chart': typeof ChartLazyRoute
  '/logister': typeof LogisterLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/chart' | '/logister'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/chart' | '/logister'
  id: '__root__' | '/' | '/about' | '/chart' | '/logister'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  ChartLazyRoute: typeof ChartLazyRoute
  LogisterLazyRoute: typeof LogisterLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  ChartLazyRoute: ChartLazyRoute,
  LogisterLazyRoute: LogisterLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/chart",
        "/logister"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/chart": {
      "filePath": "chart.lazy.tsx"
    },
    "/logister": {
      "filePath": "logister.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
